# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  buildConfiguration: 'Release'
  dockerImageNameWeb: tv-show-reminder
  ReleaseVersion: $(MajorVersion).$(Rev:r)

steps:

- task: DotNetCoreInstaller@0
  displayName: 'Use .NET Core sdk 2.2.203'
  inputs:
    version: 2.2.203

- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'Build, Configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'Run unit tests'
  inputs:
    command: 'test'
    arguments: '--configuration $(BuildConfiguration) /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:Exclude="[xunit*]*"'
    projects: 'test/**/*.csproj'
    nobuild: true

- script: |
    dotnet tool install -g dotnet-reportgenerator-globaltool
    reportgenerator -reports:$(Build.SourcesDirectory)/test/**/coverage.cobertura.xml -targetdir:$(Build.SourcesDirectory)/CodeCoverage -reporttypes:Cobertura
  displayName: 'Create code coverage report'

- task: PublishCodeCoverageResults@1
  displayName: 'Publish code coverage report'
  inputs:
    codeCoverageTool: 'Cobertura'
    summaryFileLocation: '$(Build.SourcesDirectory)/CodeCoverage/Cobertura.xml'
    reportDirectory: '$(Build.SourcesDirectory)/CodeCoverage'

- script: |
    docker build -t $(dockerId)/$(dockerImageNameWeb):latest -t $(dockerId)/$(dockerImageNameWeb):$(ReleaseVersion) .
  displayName: 'Build Docker images'

- script: |
    echo "$(dockerPassword)" | docker login -u "$(dockerId)" --password-stdin
#    docker push $(dockerId)/$(dockerImageNameWeb):$(ReleaseVersion)
#    docker push $(dockerId)/$(dockerImageNameWeb):latest
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  displayName: 'Publish Docker images (from master branch)'