version: '3'
services:
  web:
    image: jonasfred/tv-show-reminder:latest
    ports:
     - "8080:8080"
    environment:
     - 'AppSettings__MasterPassword=replace-me'
     - 'ConnectionStrings__DefaultConnection=Server=127.0.0.1;Port=5432;Database=tvshowreminder_db;User Id=test_user;Password=test;'
     - 'AppSettings__JwtSecretKey=replace-me-with-something-complicated'