kind: Service
apiVersion: v1
metadata:
 labels:
  service: external-database
 name: tvshowreminderpostgres
 namespace: {{ .Values.namespace }}
spec:
 type: ExternalName
 externalName: {{ .Values.databaseService.externalName }}