apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: tv-show-reminder-web
  name: tv-show-reminder-web-deployment
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy: {}
  selector:
    matchLabels:
      app: tv-show-reminder-web
  template:
    metadata:
      labels:
        app: tv-show-reminder-web
    spec:
      containers:
      - env:
        - name: AppSettings__JwtSecretKey
          value: {{ .Values.environment.jwtSecretKey }}
        - name: AppSettings__MasterPassword
          value: {{ .Values.environment.masterPassword }}
        - name: ConnectionStrings__DefaultConnection
          value: {{ .Values.environment.dbConnectionString }}
        image: jonasfred/tv-show-reminder:latest
        name: tv-show-reminder-web
        ports:
        - containerPort: {{ .Values.service.port }}
        resources: {}
      restartPolicy: {{ .Values.restartPolicy }}
status: {}
