apiVersion: v1
kind: Service
metadata:
  labels:
    app: tv-show-reminder-web
  name: tv-show-reminder-svc
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - name: "port"
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port }}
  selector:
    app: tv-show-reminder-web
status:
  loadBalancer: {}
