apiVersion: v1
kind: Service
metadata:
  labels:
    service: web
  name: tv-show-reminder-svc
spec:
  ports:
  - name: "port"
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port }}
  selector:
    service: tv-show-reminder-web
status:
  loadBalancer: {}
